cinema_app/API/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import ObtainAuthToken
from .resources import UserRegistrationView, HallModelViewSet, FilmModelViewSet, SessionModelViewSet, PurchaseModelViewSet

router = routers.SimpleRouter()
router.register(r'hall', HallModelViewSet)
router.register('film', FilmModelViewSet)
router.register('session', SessionModelViewSet)
router.register(r'session/(?P<session_id>\d+)/purchase', PurchaseModelViewSet)
router.register('registration', UserRegistrationView)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', ObtainAuthToken.as_view())
]

cinema_app/urls.py
from django.urls import path, include

urlpatterns = [
    path('api/', include('cinema_app.API.urls')),
]

django_cinema/urls.py
from django.contrib import admin
from django.urls import path, include

from cinema_app.views import Login, Logout, Register, HallCreateView, SessionCreateView, FilmCreateView, FilmListView, \
    FilmDetailView, PurchaseCreateView, SessionUpdateView, HallUpdateView, CartListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
    path('create_hall', HallCreateView.as_view(), name='create_hall'),
    path('create_session', SessionCreateView.as_view(), name='create_session'),
    path('create_film', FilmCreateView.as_view(), name='create_film'),
    path('show_purchase/<int:pk>', FilmDetailView.as_view(), name='purchase_detail'),
    path('create_purchase/<int:session_id>', PurchaseCreateView.as_view(), name='purchase_create'),
    path('update_session/<int:pk>', SessionUpdateView.as_view(), name='update_session'),
    path('update_hall/<int:pk>', HallUpdateView.as_view(), name='update_hall'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('', FilmListView.as_view(), name='base'),
    path('', include('cinema_app.urls')),
]

cinema_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    total_spent = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.username} Total: {self.total_spent}'


class Hall(models.Model):
    name = models.CharField(max_length=50)
    size = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.name} Size: {self.size}'


class Film(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    date_start = models.DateField()
    date_finish = models.DateField()

    def __str__(self):
        return f'{self.name}'


class Session(models.Model):
    date = models.DateField(null=True)
    time_start = models.TimeField()
    time_end = models.TimeField()
    price = models.PositiveIntegerField()
    rest_of_seats = models.PositiveIntegerField()
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE, related_name='sessions')
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='session')

    def __str__(self):
        return f' {self.film}'


class Purchase(models.Model):
    amount = models.PositiveIntegerField()
    ticket = models.ForeignKey(Session, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Amount: {self.amount} by {self.buyer}'

cinema_app/forms.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, TimeInput, DateInput

from cinema_app.models import User, Hall, Session, Film, Purchase


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",)


class HallForm(ModelForm):
    class Meta:
        model = Hall
        fields = ('name', 'size')

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')

        if len(name) == 0:
            self.add_error('name', 'Error')
            messages.error(self.request, 'Name must be greater than 0')

        return name

    def clean_size(self):
        size = self.cleaned_data.get('size')

        if size <= 0:
            self.add_error('size', 'Error')
            messages.error(self.request, 'Size must be greater than 0')

        return size


class FilmForm(ModelForm):
    class Meta:
        model = Film
        fields = ('name', 'description', 'date_start', 'date_finish',)
        widgets = {
            'date_start': DateInput(
                attrs={
                    'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                    'class': 'form-control'
                },
            ),
            'date_finish': DateInput(
                attrs={
                    'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                    'class': 'form-control'
                }
            )
        }

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')

        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        date_start = cleaned_data.get('date_start')
        date_finish = cleaned_data.get('date_finish')

        if date_start > date_finish:
            self.add_error(None, 'Error')
            messages.error(self.request, 'enter correct date, start date must be less than end date ')

    def clean_name(self):
        name = self.cleaned_data.get('name')

        if len(name) <= 0:
            self.add_error(None, 'Error')
            messages.error(self.request, 'name should be longer')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')

        if len(description) <= 0:
            self.add_error(None, 'Error')
            messages.error(self.request, 'Description should be longer')
        return description


class SessionForm(ModelForm):
    class Meta:
        model = Session
        fields = ('time_start', 'time_end', 'price', 'hall', 'film',)
        widgets = {
            'time_start': TimeInput(
                format='%H:%M',
                attrs={
                    'type': 'time',
                },
            ),
            'time_end': TimeInput(
                format='%H:%M',
                attrs={
                    'type': 'time',
                }
            )
        }

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')

        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        hall = cleaned_data.get('hall')
        self.size = hall.size

        time_start = self.cleaned_data.get('time_start')
        time_end = self.cleaned_data.get('time_end')

        if time_start > time_end:
            self.add_error(None, 'Error')
            messages.error(self.request, 'time start must by less time end!')

        if time_start and time_end and hall:
            conflicting_sessions = Session.objects.filter(
                hall=hall,
                time_start__lt=time_end,
                time_end__gt=time_start
            )

            if self.instance:
                conflicting_sessions = conflicting_sessions.exclude(pk=self.instance.pk)

            if conflicting_sessions.exists():
                self.add_error(None, 'Error')
                messages.error(self.request, 'This session conflicts with an existing session.')

        return cleaned_data

    def clean_price(self):
        price = self.cleaned_data.get('price')

        if price <= 0:
            self.add_error(None, 'Error')
            messages.error(self.request, 'price must be greater than 0')

        return price


class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = ('amount',)

    def __init__(self, *args, **kwargs):
        if 'session_id' in kwargs:
            self.session_id = kwargs.pop('session_id')

        if 'request' in kwargs:
            self.request = kwargs.pop('request')

        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.get('amount')
        session = Session.objects.get(pk=self.session_id)
        self.session = session

        if amount <= 0:
            self.add_error(None, 'Error')
            messages.error(self.request, 'Amount must be greater than 0')
            return amount

        if amount > session.rest_of_seats:
            self.add_error(None, 'Error')
            messages.error(self.request, 'Rest of seats must be greater than amount')

cinema_app/views.py
from datetime import timedelta, date
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db import transaction
from django.shortcuts import redirect
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from cinema_app.forms import UserForm, HallForm, SessionForm, FilmForm, PurchaseForm
from cinema_app.models import Session, Film, Purchase, Hall


class AdminPassedMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class Login(LoginView):
    template_name = 'login.html'
    success_url = '/'


class Logout(LoginRequiredMixin, LogoutView):
    next_page = '/'
    login_url = 'login/'


class Register(CreateView):
    form_class = UserForm
    template_name = 'register.html'
    success_url = '/'


class HallCreateView(AdminPassedMixin, CreateView):
    form_class = HallForm
    template_name = 'create_hall.html'
    success_url = '/'
    login_url = 'login/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {'request': self.request}
        )
        return kwargs


class SessionCreateView(AdminPassedMixin, CreateView):
    form_class = SessionForm
    template_name = 'create_session.html'
    success_url = '/'
    login_url = 'login/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {"request": self.request}
        )
        return kwargs

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.rest_of_seats = form.size

        date_start = obj.film.date_start
        date_finish = obj.film.date_finish

        delta = timedelta(days=1)
        date = date_start
        while date <= date_finish:
            session = Session(
                date=date,
                time_start=obj.time_start,
                time_end=obj.time_end,
                price=obj.price,
                rest_of_seats=form.size,
                hall=obj.hall,
                film=obj.film
            )
            session.save()
            date += delta

        obj.save()
        return super().form_valid(form=form)

    def form_invalid(self, form):
        return redirect('/')


class FilmCreateView(AdminPassedMixin, CreateView):
    form_class = FilmForm
    template_name = 'create_film.html'
    success_url = '/'
    login_url = 'login/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {"request": self.request}
        )
        return kwargs

    def form_invalid(self, form):
        return redirect('/')


class FilmListView(ListView):
    model = Film
    context_object_name = 'films'
    template_name = 'film_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = date.today()
        tomorrow = today + timedelta(days=1)

        day_selected = self.request.GET.get('day', 'today')
        sort_by_selected = self.request.GET.get('sort_by', 'default')

        if day_selected == 'tomorrow':
            selected_date = tomorrow
        else:
            selected_date = today

        films_selected_day = Film.objects.filter(session__date=selected_date).distinct()
        sessions_selected_day = Session.objects.filter(date=selected_date)

        if sort_by_selected == 'price':
            films_selected_day = films_selected_day.order_by('-session__price')
        elif sort_by_selected == 'time':
            films_selected_day = films_selected_day.order_by('session__time_start')

        context['films'] = films_selected_day
        context['sessions'] = sessions_selected_day
        context['sort_by'] = sort_by_selected
        context['day'] = day_selected
        context['today_date'] = today
        context['tomorrow_date'] = tomorrow

        return context

    def get_queryset(self):
        sort_by = self.request.GET.get('sort_by', 'default')
        today = date.today()

        if sort_by == 'price':
            queryset = Film.objects.filter(session__date=today).order_by('session__price')
        elif sort_by == 'time':
            queryset = Film.objects.filter(session__date=today).order_by('session__time_start')
        else:
            queryset = Film.objects.filter(session__date=today)

        return queryset


class FilmDetailView(DetailView):
    model = Session
    template_name = 'detail_film.html'
    extra_context = {'form': PurchaseForm()}
    login_url = 'login/'


class SessionUpdateView(AdminPassedMixin, UpdateView):
    model = Session
    fields = ('time_start', 'time_end', 'price', 'hall', 'film',)
    template_name = 'update_session.html'
    queryset = Session.objects.all()
    success_url = '/'
    login_url = 'login/'


class HallUpdateView(AdminPassedMixin, UpdateView):
    model = Hall
    fields = ('name', 'size',)
    template_name = 'update_hall.html'
    queryset = Hall.objects.all()
    success_url = '/'
    login_url = 'login/'


class PurchaseCreateView(CreateView):
    form_class = PurchaseForm
    template_name = 'purchase_create.html'
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {"session_id": self.kwargs['session_id'], "request": self.request}
        )
        return kwargs

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.ticket = form.session
        obj.buyer = self.request.user
        total_money = obj.ticket.price * obj.amount
        obj.buyer.total_spent += total_money
        obj.ticket.rest_of_seats -= obj.amount
        with transaction.atomic():
            obj.ticket.save()
            obj.buyer.save()
            obj.save()
        return super().form_valid(form=form)

    def form_invalid(self, form):
        return redirect('/')


class CartListView(LoginRequiredMixin, ListView):
    model = Purchase
    template_name = 'cart.html'
    queryset = Purchase.objects.all()
    login_url = 'login/'

cinema_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-light" data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand">Cinema</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'base' %}">Home</a>
                </li>
                {% if request.user.is_superuser == True %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_hall' %}">Hall</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_session' %}">Session</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_film' %}">Film</a>
                </li>
            </ul>

            {% endif %}
            <li class="nav-item dropdown d-flex navbar-brand mb-0 h1" data-bs-theme="white">


                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    {% if user.is_authenticated %}

                    {{ user }}

                    {% else %}

                    New here? Join us by signing up!

                    {% endif %}

                </a>

                <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                    {% endif %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                </ul>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item d-flex"><a class="nav-link  navbar-brand"
                                           data-bs-theme="white"
                                           href="{% url 'cart' %}">Cart</a>
                {% endif %}
            </li>

        </div>
    </div>
</nav>

{% if messages %}
<ul class="messages btn bg-warning center">
    {% for message in messages %}
    <li
    {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
{% block content %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link"
                                 href="{% url 'home' %}?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% endif %}
        {% for page in paginator.page_range %}
        <li class="page-item"><a class="page-link"
                                 href="{% url 'home' %}?page={{ page }}">{{ page }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link"
                                 href="{% url 'home' %}?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}


</body>
</html>

cinema_app/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <h1>Your cart:</h1>
    <br>
    <h2>{{ user }}</h2><br>

    {% for purchase in purchase_list %}
    {% if purchase.buyer == request.user %}

            Film: {{ purchase.ticket.film.name }} >>> Bought: {{ purchase.amount }}>>
        Session: {{ purchase.ticket.time_start }} >> Date: {{ purchase.ticket.film.date_start }}<br>

        {% endif %}
    {% endfor %}
{% endblock %}

cinema_app/templates/create_film.html
{% extends 'base.html' %}

{% block content %}
    <br>

    <form class="form-control form-control-lg" method="post">{% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Save">

    </form>
{% endblock %}

cinema_app/templates/create_hall.html
{% extends 'base.html' %}

{% block content %}
    <br>

    <form class="form-control form-control-lg" method="post">{% csrf_token %}

        {{ form.as_p }}


        <input type="submit" value="Create Hall">

    </form>
{% endblock %}

cinema_app/templates/create_session.html
{% extends 'base.html' %}

{% block content %}
    <br>

    <form class="form-control form-control-lg" method="post">{% csrf_token %}

        {{ form.as_p }}

        <input type="hidden" name="next" value="/">
        <input type="submit" value="Create Session">

    </form>
{% endblock %}

cinema_app/templates/detail_film.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ session.film.name }}</h2>
    <p>{{ session.film.description }}</p>


        <form method="post" action="{% url 'purchase_create' session.id %}">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit">Buy</button>
        </form>

{% endblock %}

cinema_app/templates/film_list.html
{% extends 'base.html' %}

{% block content %}<br>

    <div style="width: 100%; height: auto; display: flex; justify-content: center">
        <form>
            <label>
                <select name="day" onchange="this.form.submit()">
                    <option value="today" {% if day == 'today' %}selected{% endif %}>Today</option>
                    <option value="tomorrow" {% if day == 'tomorrow' %}selected{% endif %}>Tomorrow</option>
                </select>
            </label>
            <label>
                <select name="sort_by" onchange="this.form.submit()">
                    <option value="default" {% if sort_by == 'default' %}selected{% endif %}>Default sorting</option>
                    <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Sort by price</option>
                    <option value="time" {% if sort_by == 'time' %}selected{% endif %}>Sort by time</option>
                </select>
            </label>
        </form>
    </div>

    <div class="container">
        <h2>{% if day == 'today' %} Today {{ today_date }} {% else %} Tomorrow {{ tomorrow_date }} {% endif %}</h2>
        <div class="row row-cols-4">
            {% if films %}
                {% for film in films %}
                    <div class="col">
                        <div class="card mb-3 mx-auto" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ film.name }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ film.description }}</h6>
                                {% for session in film.session.all %}
                                    {% if session.date == today_date %}
                                        {% with hall=session.hall %}
                                            <p class="card-text">Hall: {{ hall.name }}</p>
                                            <p class="card-text">{{ session.time_start }} - {{ session.time_end }}</p>
                                            <p class="card-text">Price: {{ session.price }}</p>
                                            <p class="card-text">Available seats: {{ session.rest_of_seats }}</p>

                                            {% if user.is_authenticated %}
                                                <a href="{% url 'purchase_detail' session.id %}"
                                                   class="btn btn-success">Buy Tickets</a>
                                            {% endif %}

                                            {% if session.rest_of_seats == hall.size and user.is_superuser %}
                                                <a href="{% url 'update_session' session.id %}" class="btn btn-danger">Edit
                                                    session</a>
                                                {% if not hall.sessions.exists %}
                                                    <a href="{% url 'update_hall' hall.id %}" class="btn btn-danger">Update
                                                        Hall</a>
                                                {% endif %}
                                            {% endif %}
                                            <p><<<>>></p>
                                        {% endwith %}
                                    {% endif %}
                                {% empty %}
                                    <p>No sessions available</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <p>No films available {% if day == 'today' %} today {% else %} tomorrow {% endif %}</p>
                {% endfor %}
            {% else %}
                <p>No films available {% if day == 'today' %} today {% else %} tomorrow {% endif %}</p>
            {% endif %}
        </div>
    </div>


{% endblock %}

cinema_app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

cinema_app/templates/purchase_create.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="hidden" name="session_id" value="{{ session.pk }}">

        <button type="submit">Buy Ticket</button>
    </form>
{% endblock %}

cinema_app/templates/register.html
{% extends "base.html" %}
{% block title %} Registration{% endblock %}

{% block content %}
<h1>Registration</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>
<p class="text-center">If you already have an account, <a href="{% url 'login' %}">Log in</a> instead.</p>
{% endblock %}

cinema_app/templates/update_hall.html
{% extends 'base.html' %}

{% block content %}<br>

    <form method="post">{% csrf_token %}

            {{ form.as_p }}

            <button type="submit" value="update" class="btn btn-success">UPDATE</button>

        </form>

{% endblock %}

cinema_app/templates/update_session.html
{% extends 'base.html' %}

{% block content %}<br>

    <form method="post">{% csrf_token %}

            {{ form.as_p }}

            <button type="submit" value="update" class="btn btn-success">UPDATE</button>

        </form>

{% endblock %}